# Generated by Django 2.0.6 on 2018-07-12 01:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('experience_name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('main_task', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publication_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('year', models.IntegerField()),
                ('venue_name', models.CharField(max_length=500)),
                ('publication_type', models.CharField(choices=[('conf', 'conference'), ('jour', 'journal'), ('patn', 'patent')], max_length=4)),
                ('authors', models.TextField()),
                ('volume', models.CharField(max_length=20)),
                ('number_v', models.CharField(max_length=20)),
                ('page_v', models.CharField(max_length=20)),
                ('source_code', models.FileField(upload_to='codes/')),
                ('manuscript', models.FileField(upload_to='manuscript/')),
                ('demo_link', models.SlugField()),
            ],
        ),
        migrations.RenameField(
            model_name='member',
            old_name='cn_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='department',
            new_name='name_en',
        ),
        migrations.RemoveField(
            model_name='member',
            name='en_name',
        ),
        migrations.AddField(
            model_name='member',
            name='biograph',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(default=None, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='research_interests',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='telephone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Miss', 'Miss'), ('Dr', 'Dr.'), ('Prof', 'Prof.'), ('A_Prof', 'A/Prof.')], default='Mr', max_length=10),
        ),
        migrations.AddField(
            model_name='publication',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Member'),
        ),
        migrations.AddField(
            model_name='experience',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Member'),
        ),
    ]
