# Generated by Django 2.0.6 on 2018-07-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='demo_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
